export default {
  name: "",
  phone_number: "",
  email: "",
  province_id: "",
  district_id: "",
  password: "",
  password_confirmation: "",
  id_number: "",
  country_id: "",
  bank_id: "",
  brand_id: "",
  type_staff: "",
  titles_id: "",
  collateral: "",
  interest_rate: "",
  suggested_content: "",
  type_customer: "",
  career_id: "",
  amount: "",
  days: "",
  images: "",
  descriptions: "",
  description: "",
  price: "",
  payment_date: "",
  type_id: "",
  step: "",
  title_id: "",
  title: "",
  amount: "",
  purpose: "",
  beneficiary: "",
  disbursement_id:"",
  account_outstanding:"",
  close_balance:"",
  interest:"",
  opening_balance:"",
  principal:"",
  total:"",
};
